type Student ={
    firstName:string
    lastName:string
    fullName:string
    assessmentDate:string
    phone:string
    email:string
    employer:string
    job:string
    inConstruction:string
    hasOsha10Card:string
    address:string
    borough:string
    councilDistrict:string
    isNychaResident:string
    development:string
    hasValidId:string
    assessment:string
    id:string
    certificate:string
    osha30Card:string
}
